version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: adventureworks-sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: AdventureWorksAPI/Dockerfile
    container_name: adventureworks-api
    environment:
      # Use your local SQL Server; host.docker.internal works on Windows/Mac
      ConnectionStrings__AdventureWorksConnection: "Server=sqlserver,1433;Database=AdventureWorks2016;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver

  frontend:
    build:
      context: .
      dockerfile: adventureworks-ui/Dockerfile
    container_name: adventureworks-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5000" # React/Next can read this

volumes:
  sqlserver-data:
